project_name: para

builds:
  - dir: para
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/felicianotech/para/para/cmd.version={{ .Version }} -extldflags "-static"

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - LICENSE
      - README.md
    replacements:
      darwin: macos

nfpms:
  - file_name_template: "{{ .ProjectName }}-v{{ .Version }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    homepage: "https://github.com/FelicianoTech"
    maintainer: "Ricardo N Feliciano"
    description: "A useful tool for software package manager analytics."
    license: MIT
    formats:
      - deb
    bindir: /usr/bin

brews:
  - tap:
      owner: felicianotech
      name: homebrew-tap
    commit_author:
      name: "FelicianoTech"
      email: "Ricardo@Feliciano.Tech"
    folder: Formula
    homepage: "https://github.com/felicianotech/para"
    description: "A useful tool for software package manager analytics."
    test: |
      system "#{bin}/para", "help"
