version: 2.1

workflows:
  main:
    jobs:
      - test
      - build-binaries
      - build-snap:
          name: "Build Snap"
          requires:
            - build-binaries
  release:
    jobs:
      - test:
          filters:
            branches:
              ignore: /.*/
            tags:
              # Simplified SemVer regex
              only: /^v\d+\.\d+\.\d+$/
      - build-binaries:
          filters:
            branches:
              ignore: /.*/
            tags:
              # Simplified SemVer regex
              only: /^v\d+\.\d+\.\d+$/
          publish: true
      - build-snap:
          name: "Build 'stable' Snap"
          requires:
            - build-binaries
          filters:
            branches:
              ignore: /.*/
            tags:
              # Simplified SemVer regex
              only: /^v\d+\.\d+\.\d+$/
          publish-stable: true

jobs:
  test:
    docker:
      - image: cimg/go:1.15.5
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1
      - run:
          name: "Download Dependancies"
          command: cd src && go mod download
      - run:
          name: "Run Tests"
          command: cd src && go test
      - save_cache:
          key: go-mod-v1
          paths:
            - "/go/pkg/mod"
  build-binaries:
    parameters:
      publish:
        type: boolean
        default: false
    docker:
      - image: cimg/go:1.15.5
    steps:
      - checkout
      - run:
          name: "Install GoReleaser"
          command: |
            curl -sSL "https://github.com/goreleaser/goreleaser/releases/download/v0.147.1/goreleaser_Linux_x86_64.tar.gz" | sudo tar -xz -C /usr/local/bin goreleaser
            goreleaser --version
      - unless:
          condition: << parameters.publish >>
          steps:
            - run:
                name: "Build Binaries with GoReleaser"
                command: goreleaser --snapshot --skip-publish --rm-dist
      - when:
          condition: << parameters.publish >>
          steps:
            - run:
                name: "Build Binaries & Publish with GoReleaser"
                command: goreleaser
      - persist_to_workspace:
          root: "."
          paths:
            - "dist"
  build-snap:
    parameters:
      publish-edge:
        type: boolean
        default: false
      publish-stable:
        type: boolean
        default: false
    docker:
      - image: cibuilds/snapcraft:core20
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: "Build Snaps for Each Architecture"
          command: |
            # Generate a version file that Snapcraft can use
            dist/para_linux_amd64/para version --short > VERSION
            snapcraft
      - when:
          condition: << parameters.publish-edge >>
          steps:
            - run:
                name: "Publish to Snap Store in the Edge Channel"
                command: |
                  # Snapcraft Tokens are valid for 1 year. This one expires August 10th, 2021
                  echo $SNAPCRAFT_LOGIN_FILE | base64 --decode --ignore-garbage | snapcraft login --with -
                  snapcraft push *.snap --release=edge
      - when:
          condition: << parameters.publish-stable >>
          steps:
            - run:
                name: "Publish to Snap Store in the Stable Channel"
                command: |
                  # Snapcraft Tokens are valid for 1 year. This one expires August 10th, 2021
                  echo $SNAPCRAFT_LOGIN_FILE | base64 --decode --ignore-garbage | snapcraft login --with -
                  snapcraft upload *.snap --release=stable
