version: 2.1

orbs:
  gor: hubci/goreleaser@1.0

workflows:
  main:
    jobs:
      - test
      - gor/release:
          version: "0.180.3"
          go-version: "1.17.1"
          dry-run: true
  release:
    jobs:
      - test:
          filters:
            branches:
              ignore: /.*/
            tags:
              # Simplified SemVer regex
              only: /^v\d+\.\d+\.\d+$/
      - gor/release:
          version: "0.180.3"
          go-version: "1.17.1"
          filters:
            branches:
              ignore: /.*/
            tags:
              # Simplified SemVer regex
              only: /^v\d+\.\d+\.\d+$/

jobs:
  test:
    docker:
      - image: cimg/go:1.17.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1
      - run:
          name: "Download Dependancies"
          command: cd src && go mod download
      - run:
          name: "Run Tests"
          command: cd src && go test
      - save_cache:
          key: go-mod-v1
          paths:
            - "/go/pkg/mod"
